### PR TITLE
Set precinct and party

### LINKED ISSUE #39: Add Admin screen with ability to optionally configure with precinct, and additionally party.
@mcchilders says:
> for primaries, the R & D ballots need to be separated on vxencode so they can’t give the wrong one (primaries in MS have two check-in stations per polling place, one for each party, that seems to be unique to ms)

---

BAS should be configurable by a clerk/admin such that:
- it is optionally locked into a single precinct and can only encode that precinct's ballot styles
- it is optionally locked into a single party and can only encode that party's ballot styles

Configuring for *both* is the likely use case, especially in primaries, where different parties will check in at different desks, each with a BAS.

### PR DESCRIPTION
**Pull request by beausmith**
Fixes #39

### CODE REVIEW

File: src/App.tsx [hunk 1]
```diff
@@ -27,23 +28,33 @@ import './App.css'
...
 let checkCardInterval = 0
 
-const App: React.FC = () => {
+const App = () => {
   const [isProgrammingCard, setIsProgrammingCard] = useState(false)
   const [isWritableCard, setIsWritableCard] = useState(false)
   const [isClerkCardPresent, setIsClerkCardPresent] = useState(false)
   const [isPollWorkerCardPresent, setIsPollWorkerCardPresent] = useState(false)
   const [isLocked, setIsLocked] = useState(true)
+  const [
```
Comment (benadida) [inline src/App.tsx:37]: Is this necessary? Could empty vs non empty string on precinct id be enough?

**Review by benadida — APPROVED** [review]
One suggestion, non blocking, otherwise lgtm

File: src/App.tsx (hunk 1 above)
Comment (beausmith) [reply src/App.tsx:37]: I was planning to do it that way, however there is a case (when in all precincts mode) every time a precinct is selected from the precincts screen, precinctId is set, thus there needs to be another bit to flip in order to dis/enable a buttons providing navigation back to all precincts screen.
